/**
 * rootCaCert.ts
 * Root CA сертификат — генериран от scripts/generate-root-ca.mjs
 * Публичен: може да се commit-ва в repo.
 * Ползва се при Фаза 5 (верификация на подпис).
 */
export const ROOT_CA_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIBqDCCAU6gAwIBAgIQAwl012MRQ2vXtQpC3D96dDAKBggqhkjOPQQDAjBCMR4w
HAYDVQQDExVTaWduU2hpZWxkIFJvb3QgQ0EgdjExEzARBgNVBAoTClNpZ25TaGll
bGQxCzAJBgNVBAYTAkJHMB4XDTI2MDcxMDA4NTk1NVoXDTM2MDcwOTIwNTk1NVow
QjEeMBwGA1UEAxMVU2lnblNoaWVsZCBSb290IENBIHYxMRMwEQYDVQQKEwpTaWdu
U2hpZWxkMQswCQYDVQQGEwJCRzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNoq
lf6vVgQawczBHcMq+pZxCN6D20ui9+WXJWMrVAFjlaCHVeRtO02DngPAK1JwazB7
fOQQzpa0M/vwq+Xc6fujJjAkMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/
BAQDAgEGMAoGCCqGSM49BAMCA0gAMEUCIBOrkDpD3XdAbWMK4lqXS6tCwSdYotvM
Mf6/BWXEi5VyAiEArA2ACRjWsaGoEumZccNazcEKe3k81JSUfU6T++zZ+zM=
-----END CERTIFICATE-----`;
